datetime,message,state
2020-06-08 02:16:02.613000,El archivo de registro se creo satisfactoriamente,1
2020-06-08 02:19:07.200000,Proceso ejecutado satisfactoriamente,1
2020-06-08 02:24:39.157000,Proceso ejecutado satisfactoriamente,1
2020-06-08 02:25:45.406000,Proceso ejecutado satisfactoriamente,1
2020-06-08 15:43:52.504000,Proceso ejecutado satisfactoriamente,1
2020-06-08 15:44:49.356000,Proceso ejecutado satisfactoriamente,1
2020-06-08 15:46:10.176000,Proceso ejecutado satisfactoriamente,1
2020-06-08 15:50:42.154000,"Error: <type 'exceptions.SyntaxError'>, Motivo: , Linea: 19",0
2020-06-08 15:51:42.781000,"Error: <type 'exceptions.SyntaxError'>, Motivo: , Linea: 19",0
2020-06-08 15:52:35.445000,Proceso ejecutado satisfactoriamente,1
2020-06-08 15:54:42.811000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:09:43.163000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:11:26.728000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:13:05.690000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:22:50.850000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:25:25.604000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:38:22.673000,"Error: <type 'exceptions.IndexError'>, Motivo: list index out of range, Linea: 19",0
2020-06-08 16:40:47.112000,"Error: <type 'exceptions.RuntimeError'>, Motivo: No se ha configurado la ubicacion del archivo de conexion de la Enterprise Geodatabase (line 23), Linea: 19",0
2020-06-08 16:41:21.755000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:41:42.697000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:41:54.354000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:41:58.331000,"Error: <type 'exceptions.RuntimeError'>, Motivo: No se ha configurado el parametro *Analisis de tablas de archivo* para la ejecucion del proceso (line 41), Linea: 19",0
2020-06-08 16:44:40.022000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:45:59.349000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:46:11.202000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:48:55.453000,Proceso ejecutado satisfactoriamente,1
2020-06-08 16:55:30.089000,"Error: <type 'exceptions.TypeError'>, Motivo: add_registry() takes exactly 2 arguments (3 given), Linea: 19",0
2020-06-08 16:56:21.894000,Inicio de mantenimiento de Geodatabase 2020-06-08 16:56:21.894000,1
2020-06-08 16:56:26.902000,Finalizo el mantenimiento de Geodatabase 2020-06-08 16:56:26.902000,1
2020-06-08 16:56:26.917000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:00:55.180000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:01:00.157000,Finalizo el mantenimiento de Geodatabase,1
2020-06-08 17:01:00.172000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:05:57.030000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:06:14.166000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:06:19.062000,Finalizo el mantenimiento de Geodatabase,1
2020-06-08 17:06:19.084000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:08:09.416000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:08:14.082000,"Error: <type 'exceptions.TypeError'>, Motivo: Could not open SDE workspace., Linea: 19",0
2020-06-08 17:11:20.505000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:11:25.032000,"Error: <type 'exceptions.TypeError'>, Motivo: Could not open SDE workspace., Linea: 19",0
2020-06-08 17:12:38.932000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:12:43.480000,"Error: <type 'exceptions.TypeError'>, Motivo: Could not open SDE workspace., Linea: 19",0
2020-06-08 17:14:02.766000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:14:07.041000,"Error: <type 'exceptions.TypeError'>, Motivo: Could not open SDE workspace., Linea: 19",0
2020-06-08 17:19:18.614000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:19:23.097000,"Error: <type 'exceptions.TypeError'>, Motivo: Could not open SDE workspace., Linea: 19",0
2020-06-08 17:20:48.746000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:20:53.196000,"Error: <type 'exceptions.TypeError'>, Motivo: Could not open SDE workspace., Linea: 19",0
2020-06-08 17:21:14.082000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:21:22.866000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:21:36.381000,Finalizo el mantenimiento de Geodatabase,1
2020-06-08 17:21:36.396000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:44:39.300000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:45:18.256000,Proceso ejecutado satisfactoriamente,1
2020-06-08 17:45:24.549000,Inicio de mantenimiento de Geodatabase,1
2020-06-08 17:45:28.902000,Finalizo el mantenimiento de Geodatabase,1
2020-06-08 17:45:28.918000,Proceso ejecutado satisfactoriamente,1
